Repository sepandhaghighi/art, pull requests merged in 2021-12, with the labels that each got.

#185 Font wizard modification
  otherfile/font_wizard.py
Labels: enhancement

#186 Minor edits
  README.md
Labels: document

#187 Discord Badge Added
  CHANGELOG.md
  README.md
  setup.py
Labels: enhancement, document

#188 New fonts
  .github/CONTRIBUTING.md
  CHANGELOG.md
  FontList.ipynb
  README.md
  art/art.py
  art/art_param.py
  art/test2.py
  art/text_dic3.py
  otherfile/font_wizard.py
Labels: new font

#190 Width bug
  CHANGELOG.md
  art/art.py
  art/text_dic1.py
  art/text_dic2.py
  otherfile/art_decor_check.py
  otherfile/font_check.py
  otherfile/font_wizard.py
Labels: bug, enhancement

#191 Version 5.4
  .github/CONTRIBUTING.md
  .github/workflows/greetings.yml
  .github/workflows/test.yml
  AUTHORS.md
  ArtList.ipynb
  CHANGELOG.md
  DecorList.ipynb
  FontList.ipynb
  INSTALL.md
  LICENSE
  README.md
  art/art.py
  art/art_param.py
  art/test.py
  art/test2.py
  art/text_dic1.py
  art/text_dic2.py
  art/text_dic3.py
  otherfile/art_decor_check.py
  otherfile/font_check.py
  otherfile/font_wizard.py
  otherfile/gitcoin_btn.png
  otherfile/version_check.py
  setup.py
Labels: release
