Repository sepandhaghighi/art, pull requests merged in 2023-07, with the labels that each got.

#237 Space bug for some fonts {`block`, `danc4`, `nvscript`} fixed
  CHANGELOG.md
  art/art.py
  art/text_dic1.py
  art/text_dic2.py
Labels: bug

#239 Indirect fontname problem
  CHANGELOG.md
  art/art.py
  art/art_param.py
  art/test.py
  art/test2.py
Labels: bug

#243 `aprint` random mode bug fixed
  CHANGELOG.md
  art/art.py
  art/art_param.py
  art/test2.py
Labels: bug

#248 added space function to art and aprint
  AUTHORS.md
  CHANGELOG.md
  README.md
  art/art.py
Labels: enhancement, good first issue, new feature

#251 Modernize code
  AUTHORS.md
  art/__main__.py
  art/art.py
  art/art_param.py
  art/test.py
  otherfile/art_decor_check.py
  otherfile/font_check.py
  otherfile/font_wizard.py
  otherfile/version_check.py
  setup.py
Labels: enhancement

#253 Space bug fix
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  art/art.py
  art/test.py
Labels: bug, enhancement
