Repository sepandhaghighi/art, pull requests merged in 2024-11, with the labels that each got.

#286 Fix/pypi badge
  CHANGELOG.md
  README.md
Labels: document, minor

#285 Minor edits on line functionality
  README.md
  art/functions.py
  art/params.py
  art/tests/test.py
Labels: test, document

#287 `lprint` modification
  CHANGELOG.md
  README.md
  art/functions.py
  art/tests/test.py
Labels: enhancement, document

#288 Minor edits
  AUTHORS.md
  README.md
Labels: document, minor

#289 Version 6.4
  .github/ISSUE_TEMPLATE/bug_report.yml
  ArtList.ipynb
  CHANGELOG.md
  DecorList.ipynb
  FontList.ipynb
  INSTALL.md
  SECURITY.md
  art/params.py
  art/tests/test.py
  otherfile/meta.yaml
  otherfile/version_check.py
  setup.py
Labels: release
