Repository sepandhaghighi/art, pull requests merged in 2025-04, with the labels that each got.

#294 New fonts
  CHANGELOG.md
  FontList.ipynb
  README.md
  art/data/fonts3.py
  art/params.py
  art/tests/test2.py
Labels: new font

#295 `Ubuntu-20.04` --> `Ubuntu-22.04`
  .github/workflows/publish_conda.yaml
  .github/workflows/publish_pypi.yml
  .github/workflows/test.yml
  CHANGELOG.md
  INSTALL.md
Labels: test

#297 Version 6.5
  .github/ISSUE_TEMPLATE/bug_report.yml
  ArtList.ipynb
  CHANGELOG.md
  DecorList.ipynb
  FontList.ipynb
  INSTALL.md
  SECURITY.md
  art/params.py
  art/tests/test.py
  otherfile/meta.yaml
  otherfile/version_check.py
  setup.py
Labels: release

#298 Website v6.5
  ArtList.html
  DecorList.html
  FontList.html
  index.html
Labels: website

#296 Type hint
  CHANGELOG.md
  art/__main__.py
  art/functions.py
  art/utils.py
  otherfile/art_decor_check.py
  otherfile/font_check.py
  otherfile/font_wizard.py
  otherfile/version_check.py
  setup.py
Labels: enhancement, document
